import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ThemePicker } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><div className="flex justify-between pt-4 pr-12">
          <div></div> {/* Empty div for spacing */}
          <ThemePicker />
        </div>
        <div className="flex-grow">{children}</div></body>
    </html>
  );
}
